apiVersion: v1
kind: Service
metadata:
  name: doc-db
  labels:
    app: rerodoc
    tier: db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30033
      name: db
  selector:
    app: rerodoc
    tier: db
