apiVersion: v1
kind: Service
metadata:
  name: doc-tasksui
  labels:
    app: rerodoc
    tier: tasksui
spec:
  type: NodePort
  ports:
    - port: 5555
      nodePort: 30040
  selector:
    app: rerodoc
    tier: tasksui
