apiVersion: v1
kind: Service
metadata:
  name: doc-frontend
  labels:
    app: rerodoc
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30030
  selector:
    app: rerodoc
    tier: frontend
