apiVersion: v1
kind: Service
metadata:
  name: doc-indexer
  labels:
    app: rerodoc
    tier: indexer
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30031
      name: api
    - port: 9300
      nodePort: 30032
      name: cluster
  selector:
    app: rerodoc
    tier: indexer
