apiVersion: v1
kind: Service
metadata:
  name: doc-cache
  labels:
    app: rerodoc
    tier: cache
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30034
      name: cache
  selector:
    app: rerodoc
    tier: cache
